///$tab Keep
// HTMLOutput:
// LOAD
// // 	replace(replace([<!DOCTYPE html>], chr(39), '&#39;'), chr(44), '&#44;') as [<!DOCTYPE html>]
// // 	replace([<!DOCTYPE html>], chr(34), '&#34;') as [<!DOCTYPE html>]
// [<!DOCTYPE html>]
// INLINE [
// <!DOCTYPE html>
// <html>
//  <head>
//    <meta http-equiv=refresh content=10; url=http://localhost:4848/dev-hub/>
//  </head>
//  <body>
//    <p>You will be redirected to example.com soon!</p>
//  </body>
// </html>
// ]
// ;